---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}"
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "{{ .Release.Name }}"
        spec:
          serviceAccountName: "{{ .Release.Name }}"
          containers:
            - name: "{{ .Chart.Name }}"
              env:
              {{- if .Values.pushgatewayURL }}
                - name: PUSHGATEWAY_URL
                  value: "{{ .Values.pushgatewayURL }}"
              {{- end }}
                - name: LOG_LEVEL
                  value: "{{ .Values.logLevel }}"
                - name: LOG_FORMAT
                  value: "{{ .Values.logFormat }}"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: CRONJOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: "{{ .Release.Name }}"
              securityContext:
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1069
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Chart.Version }}"
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              volumeMounts:
                - name: resources
                  mountPath: /app/config/resources.yaml
                  subPath: resources.yaml
          volumes:
            - name: resources
              configMap:
                name: {{ .Release.Name }}-resources
          securityContext:
            runAsUser: 1069
            runAsGroup: 1069
            fsGroup: 1069
          restartPolicy: OnFailure