{{- if .Values.alerts }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: "{{ .Release.Name }}"
spec:
  groups:
    - name: "{{ .Release.Name }}"
      rules:
        - alert: EuthanaisaNotRunning
          expr: kube_job_complete{job_name="euthanaisa"} == 0
          for: 6h
          labels:
            namespace: nais-system
            severity: warning
          annotations:
            consequence: Workloads that should be removed, aren't.
            action: "Check logs in euthanaisa"

{{- range .Values.resources }}
        - alert: EuthanaisaErrors{{ .resource | replace "-" "_" | title }}
          expr: increase(euthanaisa_{{ .resource | replace "-" "_" }}_errors[30m]) > 0
          for: 6h
          labels:
            namespace: nais-system
            severity: warning
          annotations:
            consequence: "{{ .resource | title }} workloads that should be removed aren't."
            action: "Check euthanaisa logs for {{ .resource }}"
{{- end }}
{{- end }}