kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}"
rules:
{{- range .Values.resources }}
  - apiGroups: ["{{ .group }}"]
    resources: ["{{ .resource }}"]
    verbs: ["list", "delete"]
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}"
  apiGroup: rbac.authorization.k8s.io

