environmentKinds:
  - tenant
  - onprem
values:
  apiserverIP:
    displayName: Kubernetes apiserver IP
    computed:
      template: "{{ .Env.apiserver_endpoint }}"
  schedule:
    displayName: Cronjob schedule
    config:
      type: string
  pushgateway.endpoint:
    displayName: Pushgateway endpoint
    config:
      type: string
    computed:
      template: "http://prometheus-pushgateway.nais-system:9091"
  logLevel:
    displayName: Log level
    config:
      type: string
