// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// NewMockResourceClient creates a new instance of MockResourceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceClient {
	mock := &MockResourceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceClient is an autogenerated mock type for the ResourceClient type
type MockResourceClient struct {
	mock.Mock
}

type MockResourceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceClient) EXPECT() *MockResourceClient_Expecter {
	return &MockResourceClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockResourceClient
func (_mock *MockResourceClient) Delete(ctx context.Context, namespace string, name string) error {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResourceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockResourceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockResourceClient_Expecter) Delete(ctx interface{}, namespace interface{}, name interface{}) *MockResourceClient_Delete_Call {
	return &MockResourceClient_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, name)}
}

func (_c *MockResourceClient_Delete_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockResourceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResourceClient_Delete_Call) Return(err error) *MockResourceClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResourceClient_Delete_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) error) *MockResourceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceGroup provides a mock function for the type MockResourceClient
func (_mock *MockResourceClient) GetResourceGroup() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceGroup")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResourceClient_GetResourceGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceGroup'
type MockResourceClient_GetResourceGroup_Call struct {
	*mock.Call
}

// GetResourceGroup is a helper method to define mock.On call
func (_e *MockResourceClient_Expecter) GetResourceGroup() *MockResourceClient_GetResourceGroup_Call {
	return &MockResourceClient_GetResourceGroup_Call{Call: _e.mock.On("GetResourceGroup")}
}

func (_c *MockResourceClient_GetResourceGroup_Call) Run(run func()) *MockResourceClient_GetResourceGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceClient_GetResourceGroup_Call) Return(s string) *MockResourceClient_GetResourceGroup_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResourceClient_GetResourceGroup_Call) RunAndReturn(run func() string) *MockResourceClient_GetResourceGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceKind provides a mock function for the type MockResourceClient
func (_mock *MockResourceClient) GetResourceKind() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceKind")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResourceClient_GetResourceKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceKind'
type MockResourceClient_GetResourceKind_Call struct {
	*mock.Call
}

// GetResourceKind is a helper method to define mock.On call
func (_e *MockResourceClient_Expecter) GetResourceKind() *MockResourceClient_GetResourceKind_Call {
	return &MockResourceClient_GetResourceKind_Call{Call: _e.mock.On("GetResourceKind")}
}

func (_c *MockResourceClient_GetResourceKind_Call) Run(run func()) *MockResourceClient_GetResourceKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceClient_GetResourceKind_Call) Return(s string) *MockResourceClient_GetResourceKind_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResourceClient_GetResourceKind_Call) RunAndReturn(run func() string) *MockResourceClient_GetResourceKind_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceName provides a mock function for the type MockResourceClient
func (_mock *MockResourceClient) GetResourceName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResourceClient_GetResourceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceName'
type MockResourceClient_GetResourceName_Call struct {
	*mock.Call
}

// GetResourceName is a helper method to define mock.On call
func (_e *MockResourceClient_Expecter) GetResourceName() *MockResourceClient_GetResourceName_Call {
	return &MockResourceClient_GetResourceName_Call{Call: _e.mock.On("GetResourceName")}
}

func (_c *MockResourceClient_GetResourceName_Call) Run(run func()) *MockResourceClient_GetResourceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceClient_GetResourceName_Call) Return(s string) *MockResourceClient_GetResourceName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResourceClient_GetResourceName_Call) RunAndReturn(run func() string) *MockResourceClient_GetResourceName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockResourceClient
func (_mock *MockResourceClient) List(ctx context.Context, namespace string, opts ...ListOption) ([]*unstructured.Unstructured, error) {
	// ListOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, namespace)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*unstructured.Unstructured
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ListOption) ([]*unstructured.Unstructured, error)); ok {
		return returnFunc(ctx, namespace, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...ListOption) []*unstructured.Unstructured); ok {
		r0 = returnFunc(ctx, namespace, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*unstructured.Unstructured)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...ListOption) error); ok {
		r1 = returnFunc(ctx, namespace, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockResourceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - opts ...ListOption
func (_e *MockResourceClient_Expecter) List(ctx interface{}, namespace interface{}, opts ...interface{}) *MockResourceClient_List_Call {
	return &MockResourceClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, namespace}, opts...)...)}
}

func (_c *MockResourceClient_List_Call) Run(run func(ctx context.Context, namespace string, opts ...ListOption)) *MockResourceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ListOption
		variadicArgs := make([]ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ListOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockResourceClient_List_Call) Return(unstructureds []*unstructured.Unstructured, err error) *MockResourceClient_List_Call {
	_c.Call.Return(unstructureds, err)
	return _c
}

func (_c *MockResourceClient_List_Call) RunAndReturn(run func(ctx context.Context, namespace string, opts ...ListOption) ([]*unstructured.Unstructured, error)) *MockResourceClient_List_Call {
	_c.Call.Return(run)
	return _c
}
